# html lang
language: ja

# header
site_brand_name: PAWNYABLE

menu:
  Practice: /practice/
  About: /about/

# stylesheets loaded in the <head>
stylesheets:
- /css/style.css

# scripts loaded in the end of the body
scripts:
- /js/frame.js

# favicon
favicon: /favicon.png

date_format: MMM D, YYYY

# profile
profile:
  description: "Pawnyableã¯ã€ä¸­ã€œä¸Šç´šè€…ãŒpwn(Binary Exploitation)ã‚’å‹‰å¼·ã™ã‚‹ãŸã‚ã®è³‡æ–™ã§ã™ã€‚"
  image: /pawnyable.png
  langs:
    "English": /#
    "ç®€ä½“ä¸­æ–‡": /#
    "í•œêµ­ì–´": /#
  links:
    "ğŸ¤ Linux Userland": /linux-userland/
    "ğŸº Linux Kernel": /linux-kernel/
    "ğŸ‘ Windows Userland [å·¥äº‹ä¸­]": #/windows-user/
    "ğŸ» Windows Kernel [å·¥äº‹ä¸­]": #/windows-kernel/
    "ğŸ¼ Browser Exploit [å·¥äº‹ä¸­]": #/browser/
    "ğŸ° VM Escape [å·¥äº‹ä¸­]": #/vm-escape/
    "ğŸ¦ Android/iOS Exploit [å·¥äº‹ä¸­]": #/phone/
    "ğŸ¯ and more...? [å·¥äº‹ä¸­]": #/misc/

# footer
footer:
  copyright_info:
    enable: false
    author:

  powered_by: # Powered by Hexo & Frame
    enable: false

  other_info:
    enable: true
    content: Â© 2023 ptr-yudai ğŸˆ

# color mode: default / classic / dark
color_mode: default

# mathjax setting
# note: need to install the hexo plugin for math: https://github.com/hexojs/hexo-math
mathjax_enable: false
